 [build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions.daily-quotes]
  schedule = "0 16 * * *" 
  
[[headers]]
  for = "/community"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
